server:
  port: 9999

# 服务名称
spring:
  application:
    name: coco-gateway

  redis:
    url: redis://:@localhost:6379

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8850
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          enabled: true

      routes:
        - id: coco-auth
#          uri: http://localhost:3100
          uri: lb://coco-auth
          predicates:
            - Path=/auth/**
          filters:
            - CaptchaVerificationFilter
            - PasswordDecodeFilter
        - id: coco-upms
          uri: lb://coco-upms
          predicates:
            - Path=/admin/**

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

coco:
  gateway:
    encode-key: 'thanks,pig4cloud'